### ISSUE TITLE
please add tag for 2.0 release

### ISSUE THREAD

**Issue by pravi** [chaijs/deep-eql#32]
we take github tarballs for debian packages and without tags manually finding a commit is hard

**Comment by lucasfcosta** [comment]
@pravi thanks for the issue! You're totally right, we should've tagged the `2.0.0` version.
I'll cc @keithamus here because he knows better about how our tag/release system works. The last time I tagged a commit I accidentally ended up releasing a new version of a package 😆 

Anyway, don't worry, we'll do it. Thanks again for pointing this 😄

**Comment by keithamus** [comment]
Hey @pravi sorry this took so long. `2.0.0` and `2.0.1` are tagged. They should be tagged automatically from now on 🤞
